CC = g++
CFLAGS = -c -Wall

all: client server

client: client.o
        $(CC) client.o -o client

client.o: client.cpp
        $(CC) $(FLAGS) -c client.cpp

server: server.o
        $(CC) server.o -o server

server.o: server.cpp
        $(CC) $(FLAGS) -c server.cpp

clean:
        rm *o client server
